### ISSUE TITLE
Set up CI/CD Pipeline with GitHub Actions

### ISSUE THREAD

**Issue by git-kubik** [git-kubik/NexaNest#21]
## Description
Implement a comprehensive CI/CD pipeline using GitHub Actions for automated testing, code quality checks, and deployment.

## Scope
Create GitHub Actions workflows for the entire project covering all services and the frontend.

## Tasks
- [ ] Create base workflow structure
  - [ ] `.github/workflows/` directory setup
  - [ ] Reusable workflow components
  - [ ] Environment configuration
- [ ] Implement CI workflow (`ci.yml`)
  - [ ] Trigger on PR and push to main
  - [ ] Python service testing (auth, portfolio, analytics, etc.)
  - [ ] Frontend testing (when implemented)
  - [ ] Code quality checks
  - [ ] Security scanning
- [ ] Add code quality jobs
  - [ ] Python linting (ruff, black)
  - [ ] TypeScript/JavaScript linting (ESLint)
  - [ ] Code formatting checks
  - [ ] Type checking (mypy for Python, tsc for TypeScript)
- [ ] Implement test coverage
  - [ ] Run pytest with coverage for Python services
  - [ ] Upload coverage reports to Codecov
  - [ ] Enforce minimum coverage thresholds
- [ ] Add security scanning
  - [ ] Dependency vulnerability scanning
  - [ ] Secret scanning
  - [ ] SAST (Static Application Security Testing)
- [ ] Create CD workflow (`deploy.yml`)
  - [ ] Build Docker images
  - [ ] Push to registry
  - [ ] Deploy to staging (manual approval)
  - [ ] Deploy to production (manual approval)
- [ ] Add documentation checks
  - [ ] MkDocs build validation
  - [ ] Markdown linting
  - [ ] Link checking
- [ ] Implement caching strategies
  - [ ] Python dependencies (uv cache)
  - [ ] Node modules cache
  - [ ] Docker layer caching
- [ ] Set up matrix testing
  - [ ] Multiple Python versions
  - [ ] Multiple Node versions
  - [ ] Different OS environments
- [ ] Configure branch protection
  - [ ] Require PR reviews
  - [ ] Require status checks to pass
  - [ ] Enforce linear history

## Workflow Structure
```yaml
# Example structure
name: CI
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-python:
    strategy:
      matrix:
        service: [auth, portfolio, analytics]
    steps:
      - Test each service
      - Check coverage
      - Upload results
```

## Priority
🟡 **Medium** - Essential for code quality and deployment automation

## Files to Create
- `.github/workflows/ci.yml`
- `.github/workflows/deploy.yml`
- `.github/workflows/security.yml`
- `.github/workflows/docs.yml`
- `.github/dependabot.yml`
- `.github/actions/setup-python/action.yml`
- `.github/actions/setup-node/action.yml`

## Success Criteria
- All PRs automatically tested
- Code quality enforced
- Security vulnerabilities detected
- Automated deployments working
- Coverage reports generated
- Documentation validated
